const SearchTypes = {
    SEARCH_RESULT: "SEARCH_RESULT",
    OLD_RESULT: "OLD_RESULT",
    LOADING: "LOADING",
    FETCHING_MORE: "FETCHING_MORE",
    MAX_REACHED: "MAX_REACHED",
    RESET_SEARCH_STATE: "RESET_SEARCH_STATE",
    OPEN_SEARCH_PROMPT: "OPEN_SEARCH_PROMPT",
}

export default SearchTypes;